{\rtf1\ansi\ansicpg1252\cocoartf2758
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 ---------------SILVER TASK VERSION 2-------------------\
CREATE OR REPLACE TASK MTL_DEV_DB.MTL_SILVER.TK_BZ_SL_EMPLOYEE\
    WAREHOUSE = COMPUTE_WH\
    SCHEDULE = 'USING CRON 30 18-18 * * * UTC'\
    WHEN SYSTEM$STREAM_HAS_DATA('BZ_EMPLOYEE_ST')\
    AS \
INSERT INTO MTL_DEV_DB.MTL_SILVER.SL_EMPLOYEE\
WITH CTE_STREAM AS (\
SELECT *,\
ROW_NUMBER() OVER (PARTITION BY EMP_NO,EMP_TYPE,EMP_NAME,EMAIL,PHONE_NUMBER,SALARY,ADDRESS,GENDER,DOB,HIRE_DATE,INSERT_DATE,UPDATE_DATE\
ORDER BY EMP_NO,EMP_TYPE,EMP_NAME,EMAIL,PHONE_NUMBER,SALARY,ADDRESS,GENDER,DOB,HIRE_DATE,INSERT_DATE,UPDATE_DATE DESC) AS ROW_NUM \
FROM MTL_DEV_DB.MTL_BRONZE.BZ_EMPLOYEE_ST)\
SELECT \
EMP_TYPE,\
EMP_NAME,\
EMP_NO,\
EMAIL,\
PHONE_NUMBER,\
SALARY,\
ADDRESS,\
GENDER,\
DOB,\
HIRE_DATE,\
INSERT_DATE,\
UPDATE_DATE FROM CTE_STREAM WHERE ROW_NUM = 1;\
\
ALTER TASK MTL_DEV_DB.MTL_SILVER.TK_BZ_SL_EMPLOYEE RESUME;\
ALTER TASK MTL_DEV_DB.MTL_SILVER.TK_BZ_SL_EMPLOYEE SUSPEND;\
SHOW TASKS;\
}